### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by Decode84**
Here comes a big update - With maybe breaking changes. But everything works on my machine.

### CODE REVIEW

**Comment by Decode84** [comment]
DO NOT MERGE

**Comment by Decode84** [comment]
Kun merge hvis det er okay.

**Review by SilverBrother — APPROVED** [review]
Most is just file moving and additional classes.

**Comment by Decode84** [comment]
Tænker bare at jeg flytter rundt på det hele når alt er ved at være færdig. :D

**Comment by Decode84** [comment]
Most of the fixed bugs has been fixed by now or implemented again.

**Pull request closed without merging**
