### PR TITLE
Database method to place it in memory of program instead

### PR DESCRIPTION
**Pull request by SilverBrother**
Faster Performance
+ added OriReference to tables in database

### CODE REVIEW

**Comment by SilverBrother** [comment]
WARNING! HAS NOT BEEN TESTED BECAUSE IS WORKS WITH DATABASE AND UNIT TEST ISN'T SUPPOSE TO BE OVER THIRD PARTIES.

**Comment by SilverBrother** [comment]
This

**Comment by SilverBrother** [comment]
Is

**Comment by SilverBrother** [comment]
Purely

**Comment by SilverBrother** [comment]
Cancer

**Comment by SilverBrother** [comment]
For

**Comment by SilverBrother** [comment]
Spambox <3

**Review by Uewotm90 — APPROVED** [review]
Looks good

**Comment by Uewotm90** [comment]
Mærkeligt branchnavn ngl

**Pull request merged**
